#!/bin/bash
# Script para colocar imagens oficiais em /public
# Instruções para o usuário

echo "═══════════════════════════════════════════════════════════════"
echo "  PLANO DE TRABALHO SES-SP 2026 - Setup de Imagens Oficiais"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📋 PASSO 1: Preparar Imagens"
echo "───────────────────────────"
echo "Você recebeu 2 imagens oficiais:"
echo "  1. Logo colorida (com cores vermelha, preta e branca)"
echo "  2. Logo branca (monocromática)"
echo ""
echo "📁 PASSO 2: Salvar em /public"
echo "───────────────────────────"
echo "Salve os arquivos EXATAMENTE com estes nomes:"
echo ""
echo "  /public/logo-colorida.png"
echo "  └─ Usar em: Login + Documento PDF"
echo ""
echo "  /public/logo-branca.png"
echo "  └─ Usar em: Header (topo do sistema)"
echo ""
echo "✅ PASSO 3: Verificar"
echo "───────────────────"
echo "Após salvar as imagens:"
echo "  • Servidor fará reload automático"
echo "  • Abra http://localhost:3004 no navegador"
echo "  • Logo colorida aparecerá na tela de login"
echo "  • Logo branca aparecerá no cabeçalho após login"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  IMPORTANTE:"
echo "   • Não alterar nomes de arquivos"
echo "   • Manter formatos PNG com transparência"
echo "   • Não aplicar filtros ou efeitos"
echo "   • Manter resolução original"
echo ""
echo "🔗 Referências:"
echo "   • Arquivo de instruções: IMAGES_SETUP.md"
echo "   • Guia visual e checklist: MODO_OPERACIONAL.md"
echo "   • Código configurado: App.tsx"
echo ""
echo "═══════════════════════════════════════════════════════════════"
