-- ============================================================
-- Seed: Naturezas de Despesa por Programa
-- Execute no Supabase SQL Editor após criar as tabelas principais.
-- ============================================================

-- Limpar configurações existentes (para re-seed limpo)
-- DELETE FROM public.programa_naturezas_catalogo;

-- ─── EMENDA INDIVIDUAL - CUSTEIO MAC - 2E90 ─────────────────
INSERT INTO public.programa_naturezas_catalogo (programa_id, codigo, descricao, ordem, ativo)
SELECT p.id, n.codigo, n.descricao, n.ord, true
FROM public.programas_orcamentarios p
CROSS JOIN (VALUES
  (0,  '333220', 'AUXILIO FINANCEIRO A PESQUISADORES'),
  (1,  '333235', 'CONSULTORIA'),
  (2,  '335043', 'SUBVENCOES SOCIAIS'),
  (3,  '335085', 'TRANSFERENCIAS POR MEIO DE CONTRATO DE GESTAO'),
  (4,  '337100', 'TRANSFERÊNCIAS A CONSÓRCIOS PÚBLICOS MEDIANTE CONTRATO DE RATEIO'),
  (5,  '337170', 'RATEIO PELA PARTICIPAÇÃO EM CONSÓRCIO PÚBLICO'),
  (6,  '337200', 'EXECUÇÃO ORÇAMENTÁRIA DELEGADA A CONSÓRCIOS PÚBLICOS'),
  (7,  '339030', 'MATERIAL DE CONSUMO'),
  (8,  '339033', 'PASSAGENS E DESPESAS COM LOCOMOCAO'),
  (9,  '339037', 'LOCACAO DE MAO-DE-OBRA'),
  (10, '339039', 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA'),
  (11, '339040', 'SERVICOS DE TECNOLOGIA DA INFORMACAO E COMUNICACAO - PESSOA JURIDICA')
) AS n(ord, codigo, descricao)
WHERE p.nome = 'EMENDA INDIVIDUAL - CUSTEIO MAC - 2E90'
ON CONFLICT (programa_id, codigo) DO NOTHING;

-- ─── EMENDA INDIVIDUAL - PMAE COMPONENTE CIRURGIA ────────────
INSERT INTO public.programa_naturezas_catalogo (programa_id, codigo, descricao, ordem, ativo)
SELECT p.id, n.codigo, n.descricao, n.ord, true
FROM public.programas_orcamentarios p
CROSS JOIN (VALUES
  (0,  '333220', 'AUXILIO FINANCEIRO A PESQUISADORES'),
  (1,  '333235', 'CONSULTORIA'),
  (2,  '335043', 'SUBVENCOES SOCIAIS'),
  (3,  '335085', 'TRANSFERENCIAS POR MEIO DE CONTRATO DE GESTAO'),
  (4,  '337100', 'TRANSFERÊNCIAS A CONSÓRCIOS PÚBLICOS MEDIANTE CONTRATO DE RATEIO'),
  (5,  '337170', 'RATEIO PELA PARTICIPAÇÃO EM CONSÓRCIO PÚBLICO'),
  (6,  '337200', 'EXECUÇÃO ORÇAMENTÁRIA DELEGADA A CONSÓRCIOS PÚBLICOS'),
  (7,  '339030', 'MATERIAL DE CONSUMO'),
  (8,  '339033', 'PASSAGENS E DESPESAS COM LOCOMOCAO'),
  (9,  '339036', 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA'),
  (10, '339037', 'LOCACAO DE MAO-DE-OBRA'),
  (11, '339039', 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA'),
  (12, '339040', 'SERVICOS DE TECNOLOGIA DA INFORMACAO E COMUNICACAO - PESSOA JURIDICA')
) AS n(ord, codigo, descricao)
WHERE p.nome = 'EMENDA INDIVIDUAL - PMAE COMPONENTE CIRURGIA - (PNRF/MUTIRÃO)'
ON CONFLICT (programa_id, codigo) DO NOTHING;

-- ─── EMENDA COLETIVA - PORTARIA 10.352 - CUSTEIO ─────────────
INSERT INTO public.programa_naturezas_catalogo (programa_id, codigo, descricao, ordem, ativo)
SELECT p.id, n.codigo, n.descricao, n.ord, true
FROM public.programas_orcamentarios p
CROSS JOIN (VALUES
  (0,  '333220', 'AUXILIO FINANCEIRO A PESQUISADORES'),
  (1,  '333235', 'CONSULTORIA'),
  (2,  '335043', 'SUBVENCOES SOCIAIS'),
  (3,  '335085', 'TRANSFERENCIAS POR MEIO DE CONTRATO DE GESTAO'),
  (4,  '337100', 'TRANSFERÊNCIAS A CONSÓRCIOS PÚBLICOS MEDIANTE CONTRATO DE RATEIO'),
  (5,  '337170', 'RATEIO PELA PARTICIPAÇÃO EM CONSÓRCIO PÚBLICO'),
  (6,  '337200', 'EXECUÇÃO ORÇAMENTÁRIA DELEGADA A CONSÓRCIOS PÚBLICOS'),
  (7,  '339004', 'CONTRATACAO POR TEMPO DETERMINADO - PES.CIVIL'),
  (8,  '339030', 'MATERIAL DE CONSUMO'),
  (9,  '339033', 'PASSAGENS E DESPESAS COM LOCOMOCAO'),
  (10, '339036', 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA'),
  (11, '339037', 'LOCACAO DE MAO-DE-OBRA'),
  (12, '339039', 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA'),
  (13, '339040', 'SERVICOS DE TECNOLOGIA DA INFORMACAO E COMUNICACAO - PESSOA JURIDICA')
) AS n(ord, codigo, descricao)
WHERE p.nome = 'EMENDA COLETIVA - PORTARIA 10.352 - CUSTEIO DE SERVIÇOS DA ATENÇÃO ESPECIALIZADA À SAÚDE'
ON CONFLICT (programa_id, codigo) DO NOTHING;

-- ─── EMENDA COLETIVA - PORTARIA 10.352 - CARRETA ─────────────
INSERT INTO public.programa_naturezas_catalogo (programa_id, codigo, descricao, ordem, ativo)
SELECT p.id, n.codigo, n.descricao, n.ord, true
FROM public.programas_orcamentarios p
CROSS JOIN (VALUES
  (0,  '333220', 'AUXILIO FINANCEIRO A PESQUISADORES'),
  (1,  '333235', 'CONSULTORIA'),
  (2,  '335043', 'SUBVENCOES SOCIAIS'),
  (3,  '335085', 'TRANSFERENCIAS POR MEIO DE CONTRATO DE GESTAO'),
  (4,  '337100', 'TRANSFERÊNCIAS A CONSÓRCIOS PÚBLICOS MEDIANTE CONTRATO DE RATEIO'),
  (5,  '337170', 'RATEIO PELA PARTICIPAÇÃO EM CONSÓRCIO PÚBLICO'),
  (6,  '337200', 'EXECUÇÃO ORÇAMENTÁRIA DELEGADA A CONSÓRCIOS PÚBLICOS'),
  (7,  '339004', 'CONTRATACAO POR TEMPO DETERMINADO - PES.CIVIL'),
  (8,  '339030', 'MATERIAL DE CONSUMO'),
  (9,  '339033', 'PASSAGENS E DESPESAS COM LOCOMOCAO'),
  (10, '339036', 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA'),
  (11, '339037', 'LOCACAO DE MAO-DE-OBRA'),
  (12, '339039', 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA'),
  (13, '339040', 'SERVICOS DE TECNOLOGIA DA INFORMACAO E COMUNICACAO - PESSOA JURIDICA')
) AS n(ord, codigo, descricao)
WHERE p.nome = 'EMENDA COLETIVA - PORTARIA 10.352 - PROGRAMA AGORA TEM ESPECIALISTAS - CARRETA DA SAÚDE'
ON CONFLICT (programa_id, codigo) DO NOTHING;

-- ─── PARCELA SUPLEMENTAR - PORTARIA 10.169 - CUSTEIO ─────────
INSERT INTO public.programa_naturezas_catalogo (programa_id, codigo, descricao, ordem, ativo)
SELECT p.id, n.codigo, n.descricao, n.ord, true
FROM public.programas_orcamentarios p
CROSS JOIN (VALUES
  (0,  '333220', 'AUXILIO FINANCEIRO A PESQUISADORES'),
  (1,  '333235', 'CONSULTORIA'),
  (2,  '335043', 'SUBVENCOES SOCIAIS'),
  (3,  '335085', 'TRANSFERENCIAS POR MEIO DE CONTRATO DE GESTAO'),
  (4,  '337100', 'TRANSFERÊNCIAS A CONSÓRCIOS PÚBLICOS MEDIANTE CONTRATO DE RATEIO'),
  (5,  '337170', 'RATEIO PELA PARTICIPAÇÃO EM CONSÓRCIO PÚBLICO'),
  (6,  '337200', 'EXECUÇÃO ORÇAMENTÁRIA DELEGADA A CONSÓRCIOS PÚBLICOS'),
  (7,  '339030', 'MATERIAL DE CONSUMO'),
  (8,  '339033', 'PASSAGENS E DESPESAS COM LOCOMOCAO'),
  (9,  '339036', 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA'),
  (10, '339037', 'LOCACAO DE MAO-DE-OBRA'),
  (11, '339039', 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA'),
  (12, '339040', 'SERVICOS DE TECNOLOGIA DA INFORMACAO E COMUNICACAO - PESSOA JURIDICA')
) AS n(ord, codigo, descricao)
WHERE p.nome = 'PARCELA SUPLEMENTAR - PORTARIA 10.169 - CUSTEIO DA MÉDIA E ALTA COMPLEXIDADE'
ON CONFLICT (programa_id, codigo) DO NOTHING;

-- ─── PARCELA SUPLEMENTAR - PORTARIA 10.169 - ESPECIALISTA ────
INSERT INTO public.programa_naturezas_catalogo (programa_id, codigo, descricao, ordem, ativo)
SELECT p.id, n.codigo, n.descricao, n.ord, true
FROM public.programas_orcamentarios p
CROSS JOIN (VALUES
  (0,  '333220', 'AUXILIO FINANCEIRO A PESQUISADORES'),
  (1,  '333235', 'CONSULTORIA'),
  (2,  '335043', 'SUBVENCOES SOCIAIS'),
  (3,  '335085', 'TRANSFERENCIAS POR MEIO DE CONTRATO DE GESTAO'),
  (4,  '337100', 'TRANSFERÊNCIAS A CONSÓRCIOS PÚBLICOS MEDIANTE CONTRATO DE RATEIO'),
  (5,  '337170', 'RATEIO PELA PARTICIPAÇÃO EM CONSÓRCIO PÚBLICO'),
  (6,  '337200', 'EXECUÇÃO ORÇAMENTÁRIA DELEGADA A CONSÓRCIOS PÚBLICOS'),
  (7,  '339030', 'MATERIAL DE CONSUMO'),
  (8,  '339033', 'PASSAGENS E DESPESAS COM LOCOMOCAO'),
  (9,  '339036', 'OUTROS SERVICOS DE TERCEIROS - PESSOA FISICA'),
  (10, '339037', 'LOCACAO DE MAO-DE-OBRA'),
  (11, '339039', 'OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA'),
  (12, '339040', 'SERVICOS DE TECNOLOGIA DA INFORMACAO E COMUNICACAO - PESSOA JURIDICA')
) AS n(ord, codigo, descricao)
WHERE p.nome = 'PARCELA SUPLEMENTAR - PORTARIA 10.169 - PROGRAMA AGORA TEM ESPECIALISTA'
ON CONFLICT (programa_id, codigo) DO NOTHING;

NOTIFY pgrst, 'reload schema';
